#!/bin/bash

# Happy path where mktemp workeds
if [[ "${MOCK_MKTEMP}" -eq 1 ]]; then
    echo ./tmp/path_1
    exit 0
# Abnormal path where mktemp is not on system
elif [[ "${MOCK_MKTEMP}" -eq 2 ]]; then
    exit 1
fi

exit 1

