#!/bin/bash

# Happy path where mkdir works
if [[ "${MOCK_MKDIR}" -eq 1 ]]; then
    echo "[MOCK MKDIR] Returning pass" >&2
    exit 0
# Abnormal path where mkdir fails
elif [[ "${MOCK_MKDIR}" -eq 2 ]]; then
    echo "[MOCK MKDIR] Returning failure" >&2
    exit 1
fi

exit 1

